### ISSUE TITLE
build.gradle not loading versionName

### ISSUE THREAD

**Issue by mateusreis** [Microsoft/code-push#349]
Hi there, when I try to run:

`code-push release-react Myapp android`

It fails at:

```
Detecting android app version:
[Error]  The "android/app/build.gradle" file doesn't specify a value for the "android.defaultConfig.versionName" property.

```

On build.gradle I try:

        versionName "1.0.0"

and
        versionName "1.0"

But nothing works. 

I'm using:

react-native: 0.39.0",
react-native-code-push: ^1.16.1-beta
code-push-cli@1.12.6-beta

Thanks, 

Mateus

**Comment by silhouettes** [comment]
Hi, can you show us the full contents of `android/app/build.gradle`? 

I can maybe compare it against https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/android/app/build.gradle

**Comment by mateusreis** [comment]
Hi @silhouettes, here:


`
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"]
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
  compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
      applicationId "com.alerta"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0.9"
        ndk {
          abiFilters "armeabi-v7a", "x86"
        }
    }
  splits {
    abi {
      reset()
        enable enableSeparateBuildPerCPUArchitecture
        universalApk false  // If true, also generate a universal APK
        include "armeabi-v7a", "x86"
    }
  }
  buildTypes {
    debug {
      buildConfigField "String", "CODEPUSH_KEY", '"4ybbe96rvXymnqwAwzXfaErgbnXSEkHE_Wu-G"'
    }
    release {
      buildConfigField "String", "CODEPUSH_KEY", '"WvpvKkpsV27Ajt_JxMOVe_PDjRL7EkHE_Wu-G"'
      minifyEnabled enableProguardInReleaseBuilds
        proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"

    }
  }
  // applicationVariants are e.g. debug, release
  applicationVariants.all { variant ->
    variant.outputs.each { output ->
      // For each separate APK per architecture, set a unique version code as described here:
      // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
      def versionCodes = ["armeabi-v7a":1, "x86":2]
        def abi = output.getFilter(OutputFile.ABI)
        if (abi != null) {  // null for the universal-debug, universal-release variants
          output.versionCodeOverride =
            versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
        }
    }
  }
}

dependencies {
    compile project(':react-native-vector-icons')
    compile project(':react-native-code-push')
    compile project(':react-native-vector-icons')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile project(':react-native-code-push')
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
  from configurations.compile
    into 'libs'
}

android
{
  aaptOptions
  {
    cruncherEnabled = false
  }
  dexOptions {
    preDexLibraries = false
  }
  defaultConfig {
    // Enabling multidex support.
    multiDexEnabled true
  }
  configurations {
  }
}

`

**Comment by vladimir-kotikov** [comment]
This has been fixed in #358

**Comment by bollogo** [comment]
Hi, I still had the same problem and the issue was that I used tabs instead of whitespaces in the gradle file and therefore the versionName was found under an object with the key: "\tversionName". Hope, this might help someone still facing this issue.

**Comment by sergey-akhalkov** [comment]
Hi @bollogo, got it, thank you for the clarification and let me know if you have any questions or see any issues.

**Comment by lekeCoder** [comment]
unfortunately l am still having this issues despite having a properly structured `app/build.gradle`. what am l missing?

**Comment by punnygod** [comment]
i am facing the same issue .

**Comment by ray-holland-es** [comment]
I am getting the same issue. It appears to be a undocumented bug in `gradle-to-js` where it doesn't parse inline comments correctly.

eg:

```
project.ext.react = [
    enableHermes: true,  // clean and rebuild if changing
    // hermesFlagsRelease: ["-w", "-O", "-output-source-map"],
    // hermesFlagsStaging: ["-w", "-O", "-output-source-map"],
    // hermesFlagsDebug: ["-w", "-O", "-output-source-map"],
    bundleInStaging: true,
    devDisabledInStaging: true,
    bundleInInternalTest: true,
    bundleInRelease: true,
    deleteDebugFilesForVariant: { // Resolves hermes related bug for variants https://github.com/facebook/react-native/issues/33177
        def v -> v.name.toLowerCase().contains('release') || v.name.toLowerCase().contains('staging')
    },
]

Removing the comments (Leaving in the one for deleteDebugFilesForVariant seems fine) fixed my problem.
